name: CI
on:
  pull_request:
    branches: 
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: node_modules/.bin/ng run devfest:build:production
      - uses: w9jds/firebase-action@master
        with:
          args: use devfest-stg
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:devfest-stg
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}